  services:
    php:
      volumes:
        - ./app:/var/www/html
      build:
        dockerfile: php.Dockerfile
      expose:
        - "9000"
      depends_on:
        - db
      networks:
        - single-net
      environment:
        XDG_CONFIG_HOME: ${PSYSH_CONFIG_DIR_PATH}
        PSYSH_CONFIG_DIR: ${PSYSH_CONFIG_DIR_PATH}
        HOME: ${PSYSH_CONFIG_DIR_PATH}
    frontend:
      image: node:20-alpine
      volumes:
        - ./frontend:/var/www/frontend
        - node_modules:/var/www/frontend/node_modules
      ports:
        - "3000:3000"
      networks:
        - single-net
      environment:
        - NEXT_PUBLIC_API_URL_SERVER=http://nginx:80
        - NEXT_PUBLIC_API_URL_BROWSER=http://localhost:80
      command: sh -c "cd /var/www/frontend && npm install && npm run dev -- -H 0.0.0.0 -p 3000"
    db:
      volumes:
        - pgdata-volume:/var/lib/postgresql/data
      image: postgres
      env_file:
        - postgre.env
      ports:
        - "${POSTGRESQL_HOST_PORT}:5432"
      networks:
        - single-net
    nginx:
      image: nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
      ports:
        - "${NGINX_HOST_PORT}:80"
      depends_on:
        - php
      networks:
        - single-net
  volumes:
    pgdata-volume:
    node_modules:
  networks:
    single-net:
      driver: bridge